### ISSUE TITLE
Improve the performance of the canvas renderers

### ISSUE THREAD

**Issue by mdamien** [Linkurious/linkurious.js#211]
We have many tickets related to performance, here I try to summarize it

* [x] Optimize edge label alignment via a better measureText() #167
* [x] Add possibility to have `pre` and `post` hooks to canvas renderers #169
* [x] Cache `context.font` value when rendering #168
* [x] `onMove` render two times during a panning event #213
* [x] Improve pan/zoom smoothiness via requestAnimationFrame #222
* [x] Switching to clearRect rather than using width hack https://github.com/jacomyal/sigma.js/commit/3397bd53bbec57606314810fbd77801c6269ef90 #223 

Then benchmarks are currently in the `benchmarks` branch:

* Try it : Open dev console and then https://rawgit.com/Linkurious/linkurious.js/benchmarks/bench/index.html
* Code is here: https://github.com/Linkurious/linkurious.js/tree/benchmarks/bench
    * benchmarks should be moved to their own repo and be able to compare by commit refs

### Notes

* **With three.js, you can easily interact with 100k nodes**, this is the approach of VivaGraph.js
   * [demo](http://threejs.org/examples/#webgl_buffergeometry_particles)
* **SVG is capable of rendering 1000k animated nodes smoothly**
   * demo coming soon
* 60fps = 16ms to render a scene
* Smooth panning: **Do rendering via `requestAnimationFrame()` instead of event-based and interpolate**

### Semi-random ideas

* Batch rendering of everything
* Render only a clipped part of the graph for each change
* Do continuous rendering/progressive rendering instead of event-based rendering
* Use other people's optimized drawing platform, for example
    * mapboxgl.js : Very optimized map rendering
    * three.js : Simple API to render with WebGL
* offload rendering to server to allow very big graphs
   * graphistry-like approach for example
* Do performance comparisons with the other graph renderers
  * With a naive renderer (lines + circles + labels)
* Have automated perf tests:
  * To improve latency even for small graphs
* Lazy values (only calculated when used) (example:ApplyView)
* Different refresh rates for each feature (applyview/rescale/render)
* Use requestAnimationFrame when drawing in response to the events
* **clean sigma to only have a core code to optimize**
   * less settings, plugins included directly in the "core" (linkurious renderers, edge labels,..) as first-class inclusion
* use external librairies (rtree, eventing, rendering)

Also, articles about canvas optimizations:

* https://hacks.mozilla.org/2013/05/optimizing-your-javascript-game-for-firefox-os/
* www.html5rocks.com/en/tutorials/canvas/performance/

**Comment by sheymann** [comment]
Currently the graphical parts of each node and each edge are drawn separately, e.g. edge lines contains:

```js
context.beginPath();
context.moveTo(
      source[prefix + 'x'],
      source[prefix + 'y']
);
context.lineTo(
      target[prefix + 'x'],
      target[prefix + 'y']
);
context.stroke();
```

We may improve performance if we batch canvas calls within a single block `beginPath/stroke`. The challenge is to compile all instructions of the same graphical part (here the lines) while preserving their contextual parameters (color, shadow, etc.).

ref: http://www.html5rocks.com/en/tutorials/canvas/performance/?redirect_from_locale=fr cf. "Batch canvas calls together"

@mdamien WDYT?

**Comment by sheymann** [comment]
Can we try to remove the use of `context.save/restore` in sigma.renderers.linkurious?

**Comment by mdamien** [comment]
For the `save/restore`, all could be removed, we just have to be careful.

Having a system to batch similar things together would be excellent (active/not active, colors,..). The trade-off is hard to predict. With 8000 nodes, copying them to group them together could take a signifiant time compared to rendering them.

**Comment by mdamien** [comment]
A better breakdown with nodes and edges rendering. 

![bench](http://i.imgur.com/ZYHcDl5.png)

This begin to looks like a jsPerf test. Maybe I should switch to Benchmark.js to be more confident in my results.

**Comment by mdamien** [comment]
Also, here are a list of general ideas to improve the performance/speed feeling:

* Batch rendering of everything
* Render only a clipped part of the graph for each change
* Do continuous rendering/progressive rendering instead of event-based rendering
* Use other people's optimized drawing platform, for example
    * mapboxgl.js : Very optimized map rendering
    * three.js : Simple API to render with WebGL
* offload rendering to server to allow very big graphs
   * graphistry-like approach for example
* Do performance comparisons with the other graph renderers
* Have automated perf tests:
  * To improve latency even for small graphs

**Comment by mdamien** [comment]
And also a sample performance chart when panning:

![chart](http://i.imgur.com/aJnee6q.png)

Few things:

* For now, I only benchmark the renderCamera part, I should bench the whole "onMove"
* Extremities are rendered two-times

**Comment by sheymann** [comment]
I cannot think of a use case for "Render only a clipped part of the graph for each change" because we already use multiple layers (e.g. one layer to draw hovered elements).

Notice that batch processing is available to render edges, but it's buggy. Set `batchEdgesDrawing:true`

**Comment by mdamien** [comment]
@sheymann Clipped rendering would be useful to render only 10 labels out of 7000 for examples if the user is just messing around in small parts of the graph (like with mouse hovering)

Yep, batch processing is very buggy for now (because it's based around timeouts I think) and it's only for edges. For example, the priority could be to render the edges and then the labels. And if the user is interacting too fast, the labels wouldn't display. Batch processing would also mean grouping similar things together.

**Comment by sheymann** [comment]
@mdamien regression : the sigma setting `defaultEdgeType` is now ignored.

Example, edit renderers-linkurious-edges-shapes.html, add "defaultEdgeType: 'tapered'" to sigma settings line 133, and remove the hardcoded edge types line 110. The default edge renderer is used instead of the tapered edge renderer.

**Comment by sheymann** [comment]
> sigma.canvas.extremities.def.js:26 Uncaught ReferenceError: def is not defined

**Comment by sheymann** [comment]
defaultEdgeType is not working

**Comment by mdamien** [comment]
it was a bug where `sigma.min.js` would not be built when running `grunt build`: Corrected by https://github.com/Linkurious/linkurious.js/commit/81cc1fedebbb180525084a5e7a947a8ffbcabae0

**Comment by sheymann** [comment]
:+1:

**Comment by tylorbayer** [comment]
Any recent update on rendering large graphs with the canvas renderer? WebGL definitely is smoother but I need edge events.
